# Generated by Django 2.2.5 on 2019-09-12 22:09

from django.db import migrations
import i18nfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='published',
            field=i18nfield.fields.I18nTextField(default=False, verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=i18nfield.fields.I18nCharField(max_length=200, verbose_name='title'),
        ),
    ]
