name: Backend tests

on:
  pull_request:
    paths:
    - 'backend/**/*'
    - 'backend/*'

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432/tcp
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7.4'
      - run: pip install poetry invoke codecov
      - run: invoke setup-backend
      - name: pytest
        working-directory: backend
        run: |
            set +e
            OUTPUT=$(poetry run pytest --cov-report xml --cov=. --cov-fail-under 100)
            STATUS=$?
            echo "$OUTPUT"
            cd ..
            codecov
            exit $STATUS
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:${{ job.services.postgres.ports['5432'] }}/postgres
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7.4'
      - run: pip install poetry invoke
      - run: invoke setup-backend
      - name: pytest
        working-directory: backend
        run: poetry run pytest --integration
        env:
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
